<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <GameDir>$(MSBuildThisFileDirectory)..\..\sandbox-uuvr\CULTIC</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine.AudioModule"><HintPath>$(GameDir)\CULTIC_Data\Managed\UnityEngine.AudioModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.VRModule"><HintPath>$(GameDir)\CULTIC_Data\Managed\UnityEngine.VRModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.Netcode.Runtime"><HintPath>$(GameDir)\CULTIC_Data\Managed\Unity.Netcode.Runtime.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(GameDir)\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(GameDir)\CULTIC_Data\Managed\Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <ProjectReference Include="..\CulticVR.WorldStereoTrial\CulticVR.WorldStereoTrial.csproj" />
    <ProjectReference Include="..\CulticVR.AimPreview\CulticVR.AimPreview.csproj" />
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameDir)\CULTIC_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(GameDir)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Uuvr">
      <HintPath>$(GameDir)\BepInEx\plugins\Uuvr.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameDir)\CULTIC_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameDir)\CULTIC_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>$(GameDir)\CULTIC_Data\Managed\UnityEngine.XRModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameDir)\CULTIC_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GameDir)\CULTIC_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(GameDir)\CULTIC_Data\Managed\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
